CLASS zcl_sd_types DEFINITION
  PUBLIC FINAL
  CREATE PUBLIC.

  PUBLIC SECTION.
    TYPES: BEGIN OF ts_shipping_based,
             salesorganization TYPE vkorg,
             customer          TYPE kunag,
             operationtype     TYPE vtweg,
             departureprovince TYPE zsd_departureprovince,
             departuredistrict TYPE zsd_departuredistrict,
             originpoint       TYPE zsd_origin_point,
             arrivalprovince   TYPE zsd_arrivalprovince,
             arrivaldistrict   TYPE zsd_arrivaldistrict,
             destinationpoint  TYPE zsd_destination_point,
             routetype         TYPE zsd_routetype,
             teamdriverstatus  TYPE zsd_teamdriverstatus,
             vehicletype       TYPE zsd_vehicletype,
             vehiclebodytype   TYPE zsd_vehiclebodytype,
             temperatureregime TYPE zsd_temperatureregime,
             conditionquantity TYPE zsd_conditionquantity,
             conditionunit     TYPE zsd_conditionunit,
             conditionprice    TYPE zsd_conditionprice,
             currency          TYPE waers,
             validfrom         TYPE datab,
             validtodate       TYPE datbi,
           END OF ts_shipping_based.
    TYPES: BEGIN OF ts_km_based,
             salesorganization TYPE vkorg,
             customer          TYPE kunag,
             operationtype     TYPE vtweg,
             departureprovince TYPE zsd_departureprovince,
             departuredistrict TYPE zsd_departuredistrict,
             originpoint       TYPE zsd_origin_point,
             arrivalprovince   TYPE zsd_arrivalprovince,
             arrivaldistrict   TYPE zsd_arrivaldistrict,
             destinationpoint  TYPE zsd_destination_point,
             routetype         TYPE zsd_routetype,
             teamdriverstatus  TYPE zsd_teamdriverstatus,
             vehicletype       TYPE zsd_vehicletype,
             vehiclebodytype   TYPE zsd_vehiclebodytype,
             temperatureregime TYPE zsd_temperatureregime,
             kmstart           TYPE zsd_kmcount,
             kmend             TYPE zsd_kmcount,
             conditionunit     TYPE zsd_conditionunit,
             conditionquantity TYPE zsd_conditionquantity,
             conditionprice    TYPE zsd_conditionprice,
             currency          TYPE waers,
             validfrom         TYPE datab,
             validtodate       TYPE datbi,
           END OF ts_km_based.
    TYPES: BEGIN OF ts_pallet_based,
             salesorganization TYPE vkorg,
             customer          TYPE kunag,
             operationtype     TYPE vtweg,
             departureprovince TYPE zsd_departureprovince,
             departuredistrict TYPE zsd_departuredistrict,
             originpoint       TYPE zsd_origin_point,
             arrivalprovince   TYPE zsd_arrivalprovince,
             arrivaldistrict   TYPE zsd_arrivaldistrict,
             destinationpoint  TYPE zsd_destination_point,
             routetype         TYPE zsd_routetype,
             teamdriverstatus  TYPE zsd_teamdriverstatus,
             vehicletype       TYPE zsd_vehicletype,
             vehiclebodytype   TYPE zsd_vehiclebodytype,
             temperatureregime TYPE zsd_temperatureregime,
             quantitystart     TYPE zsd_quantity,
             quantityend       TYPE zsd_quantity,
             packettype        TYPE zsd_packagetype,
             conditionquantity TYPE zsd_conditionquantity,
             conditionprice    TYPE zsd_conditionprice,
             currency          TYPE waers,
             validfrom         TYPE datab,
             validtodate       TYPE datbi,
           END OF ts_pallet_based.
    TYPES: BEGIN OF ts_weight_based,
             salesorganization TYPE vkorg,
             customer          TYPE kunag,
             operationtype     TYPE vtweg,
             departureprovince TYPE zsd_departureprovince,
             departuredistrict TYPE zsd_departuredistrict,
             originpoint       TYPE zsd_origin_point,
             arrivalprovince   TYPE zsd_arrivalprovince,
             arrivaldistrict   TYPE zsd_arrivaldistrict,
             destinationpoint  TYPE zsd_destination_point,
             routetype         TYPE zsd_routetype,
             teamdriverstatus  TYPE zsd_teamdriverstatus,
             vehicletype       TYPE zsd_vehicletype,
             vehiclebodytype   TYPE zsd_vehiclebodytype,
             temperatureregime TYPE zsd_temperatureregime,
             quantitystart     TYPE zsd_quantity,
             quantityend       TYPE zsd_quantity,
             conditionquantity TYPE zsd_conditionquantity,
             conditionunit     TYPE zsd_conditionunit,
             conditionprice    TYPE zsd_conditionprice,
             currency          TYPE waers,
             validfrom         TYPE datab,
             validtodate       TYPE datbi,
           END OF ts_weight_based.
    TYPES: BEGIN OF ts_route_based,
             salesorganization TYPE vkorg,
             customer          TYPE kunag,
             operationtype     TYPE vtweg,
             departureprovince TYPE zsd_departureprovince,
             departuredistrict TYPE zsd_departuredistrict,
             originpoint       TYPE zsd_origin_point,
             routecode         TYPE zsd_route_code,
             routetype         TYPE zsd_routetype,
             teamdriversts     TYPE abap_boolean,
             vehicletype       TYPE zsd_vehicletype,
             vehiclebodytype   TYPE zsd_vehiclebodytype,
             temperatureregime TYPE zsd_temperatureregime,
             conditionquantity TYPE zsd_conditionquantity,
             conditionunit     TYPE zsd_conditionunit,
             conditionprice    TYPE zsd_conditionprice,
             currency          TYPE waers,
             validfrom         TYPE datab,
             validto           TYPE datbi,
           END OF ts_route_based.
    TYPES: BEGIN OF ts_fixedrent,
             salesorganization TYPE vkorg,
             customer          TYPE kunag,
             operationtype     TYPE vtweg,
             teamdriversts     TYPE abap_boolean,
             vehicletype       TYPE zsd_vehicletype,
             vehiclebodytype   TYPE zsd_vehiclebodytype,
             temperatureregime TYPE zsd_temperatureregime,
             daysworked        TYPE zsd_daysworked,
             conditionquantity TYPE zsd_conditionquantity,
             conditionunit     TYPE zsd_conditionunit,
             conditionprice    TYPE zsd_conditionprice,
             currency          TYPE waers,
             validfrom         TYPE datab,
             validto           TYPE datbi,
           END OF ts_fixedrent.
    TYPES: BEGIN OF ts_pointdiff,
             salesorganization TYPE vkorg,
             customer          TYPE kunag,
             operationtype     TYPE vtweg,
             departureprovince TYPE zsd_departureprovince,
             departuredistrict TYPE zsd_departuredistrict,
             originpoint       TYPE zsd_origin_point,
             arrivalprovince   TYPE zsd_arrivalprovince,
             arrivaldistrict   TYPE zsd_arrivaldistrict,
             destinationpoint  TYPE zsd_destination_point,
             routecode         TYPE zsd_route_code,
             routetype         TYPE zsd_routetype,
             vehicletype       TYPE zsd_vehicletype,
             vehiclebodytype   TYPE zsd_vehiclebodytype,
             temperatureregime TYPE zsd_temperatureregime,
             stopdifference    TYPE zsd_stopdifference,
             conditionquantity TYPE zsd_conditionquantity,
             conditionunit     TYPE zsd_conditionunit,
             conditionprice    TYPE zsd_conditionprice,
             currency          TYPE waers,
             validfrom         TYPE datab,
             validto           TYPE datbi,
           END OF ts_pointdiff.
    TYPES: BEGIN OF ts_kmdiff,
             salesorganization TYPE vkorg,
             customer          TYPE kunag,
             operationtype     TYPE vtweg,
             departureprovince TYPE zsd_departureprovince,
             departuredistrict TYPE zsd_departuredistrict,
             originpoint       TYPE zsd_origin_point,
             arrivalprovince   TYPE zsd_arrivalprovince,
             arrivaldistrict   TYPE zsd_arrivaldistrict,
             destinationpoint  TYPE zsd_destination_point,
             routetype         TYPE zsd_routetype,
             vehicletype       TYPE zsd_vehicletype,
             vehiclebodytype   TYPE zsd_vehiclebodytype,
             temperatureregime TYPE zsd_temperatureregime,
             conditionquantity TYPE zsd_conditionquantity,
             conditionunit     TYPE zsd_conditionunit,
             conditionprice    TYPE zsd_conditionprice,
             currency          TYPE waers,
             validfrom         TYPE datab,
             validtodate       TYPE datbi,
           END OF ts_kmdiff.
    TYPES: BEGIN OF ts_porterage,
             salesorganization  TYPE vkorg,
             customer           TYPE kunag,
             operationtype      TYPE vtweg,
             departureprovince  TYPE zsd_departureprovince,
             departuredistrict  TYPE zsd_departuredistrict,
             originpoint        TYPE zsd_origin_point,
             arrivalprovince    TYPE zsd_arrivalprovince,
             arrivaldistrict    TYPE zsd_arrivaldistrict,
             destinationpoint   TYPE zsd_destination_point,
             routetype          TYPE zsd_routetype,
             multipledrivercond TYPE zsd_teamdriverstatus,
             vehicletype        TYPE zsd_vehicletype,
             vehiclebodytype    TYPE zsd_vehiclebodytype,
             temperatureregime  TYPE zsd_temperatureregime,
             quantitystart      TYPE zsd_quantity,
             quantityend        TYPE zsd_quantity,
             conditionquantity  TYPE zsd_conditionquantity,
             conditionunit      TYPE zsd_conditionunit,
             conditionprice     TYPE zsd_conditionprice,
             currency           TYPE waers,
             validfrom          TYPE datab,
             validtodate        TYPE datbi,
           END OF ts_porterage.
    TYPES: BEGIN OF ts_waiting,
             salesorganization TYPE vkorg,
             customer          TYPE kunag,
             operationtype     TYPE vtweg,
             vehicletype       TYPE zsd_vehicletype,
             vehiclebodytype   TYPE zsd_vehiclebodytype,
             temperatureregime TYPE zsd_temperatureregime,
             minwaiting        TYPE zsd_waitingtime,
             conditionquantity TYPE zsd_conditionquantity,
             conditionunit     TYPE zsd_conditionunit,
             minconditionprice TYPE zsd_conditionprice,
             conditionprice    TYPE zsd_conditionprice,
             currency          TYPE waers,
             validfrom         TYPE datab,
             validtodate       TYPE datbi,
           END OF ts_waiting.
    TYPES: BEGIN OF ts_tollcost,
             salesorganization TYPE vkorg,
             customer          TYPE kunag,
             operationtype     TYPE zsd_operationtype,
             vehicletype       TYPE zsd_vehicletype,
             vehiclebodytype   TYPE zsd_vehiclebodytype,
             temperatureregime TYPE zsd_temperatureregime,
             routecode         TYPE zsd_route_code,
             conditionquantity TYPE zsd_conditionquantity,
             conditionunit     TYPE zsd_conditionunit,
             conditionprice    TYPE zsd_conditionprice,
             currency          TYPE waers,
             validfrom         TYPE datab,
             validtodate       TYPE datbi,
           END OF ts_tollcost.
    TYPES: BEGIN OF ty_response,
             flag  TYPE c LENGTH 1,
             tabix TYPE sy-tabix,
             field TYPE c LENGTH 20,
           END OF ty_response.

    TYPES tt_response       TYPE STANDARD TABLE OF ty_response WITH DEFAULT KEY.
    TYPES tt_shipping_based TYPE STANDARD TABLE OF ts_shipping_based WITH DEFAULT KEY.
    TYPES tt_km_based       TYPE STANDARD TABLE OF ts_km_based WITH DEFAULT KEY.
    TYPES tt_pallet_based   TYPE STANDARD TABLE OF ts_pallet_based WITH DEFAULT KEY.
    TYPES tt_weight_based   TYPE STANDARD TABLE OF ts_weight_based WITH DEFAULT KEY.
    TYPES tt_route_based    TYPE STANDARD TABLE OF ts_route_based WITH DEFAULT KEY.
    TYPES tt_fixedrent      TYPE STANDARD TABLE OF ts_fixedrent WITH DEFAULT KEY.
    TYPES tt_pointdiff      TYPE STANDARD TABLE OF ts_pointdiff WITH DEFAULT KEY.
    TYPES tt_kmdiff         TYPE STANDARD TABLE OF ts_kmdiff WITH DEFAULT KEY.
    TYPES tt_porterage      TYPE STANDARD TABLE OF ts_porterage WITH DEFAULT KEY.
    TYPES tt_waiting        TYPE STANDARD TABLE OF ts_waiting WITH DEFAULT KEY.
    TYPES tt_tollcost       TYPE STANDARD TABLE OF ts_tollcost WITH DEFAULT KEY.
ENDCLASS.



CLASS ZCL_SD_TYPES IMPLEMENTATION.
ENDCLASS.
